INSERT OVERWRITE TABLE EDUCATION_GOLDEN.EDU_EXPENDITURE_PER_STUDENT 
SELECT COUNTRY,YEAR,KEY,"PRIMARY" AS CATEGORY  FROM EDUCATION_STAGING.EDU_EXP_STUDENT_PRIMARY
UNION
SELECT COUNTRY,YEAR,KEY,"SECONDARY" AS CATEGORY  FROM EDUCATION_STAGING.EDU_EXP_STUDENT_SECONDARY
UNION
SELECT COUNTRY,YEAR,KEY,"TERTIARY" AS CATEGORY  FROM EDUCATION_STAGING.EDU_EXP_STUDENT_TERTIARY;
