INSERT OVERWRITE TABLE EDUCATION_GOLDEN.EDU_LITERACY_RATE 
SELECT COUNTRY,YEAR,KEY,"FEMALE" AS GENDER, "ADULT" AS CATEGORY  FROM EDUCATION_STAGING.EDU_LITR_YOUTH_FEMALE_AGE_15_AND_ABOVE
UNION
SELECT COUNTRY,YEAR,KEY,"MALE" AS GENDER, "ADULT" AS CATEGORY  FROM EDUCATION_STAGING.EDU_LITR_YOUTH_MALE_AGE_15_AND_ABOVE
UNION
SELECT COUNTRY,YEAR,KEY,"FEMALE" AS GENDER, "YOUTH" AS CATEGORY  FROM EDUCATION_STAGING.EDU_LITR_YOUTH_FEMALE_AGE_15_TO_24
UNION
SELECT COUNTRY,YEAR,KEY,"MALE" AS GENDER, "YOUTH" AS CATEGORY  FROM EDUCATION_STAGING.EDU_LITR_YOUTH_MALE_AGE_15_TO_24
;
